# <center>CHAPTER 4</center>

This chapter focuses on NumPy, coovering the following data structures:

ndarray (regular) - n-dimensional array object used for large arrays of numerical data

ndarray (record) - 2-dimensional array object used for tabular data organized ion columns

# <center>ARRAYS OF DATA</center>

Lists are very flexible, but can also use a lot of memory, and even have alower performance

To fix this we have the array - arrays structure other objects of the same data type in rows and columns

If we think only of numbers, 

A 1-dimensional array is a vector of real numbers (single row or column of elements only)

In more common cases, the 2-dimensional array represents an i x j matrix of elements

This concept generalizes to i x j x k cubes of elements in 3 dimensions

As well as to general n-dimensional arrays of shape i x j x k x l x ...

It is useful to have a specialized class of data structures explicitly desgined to handle arrays conveniently and efficiently. 

This is where the NumPy library comes into play, with its powerful ndarray class

But first, we introduce 2 alternatives for the handling of arrays

# <center>ARRAYS WITH PYTHON LISTS</center>

Arrays can be constructed with the built-in data structures presented in the previous chapter.

A simple list can be considered a 1-dimensional array

In [4]:
v=[0.5, 1.5, 2.5, 2.0]

Higher-dimensional arrays can eaily be constructed by nesting lists

In [5]:
m=[v, v, v] 
m

[[0.5, 1.5, 2.5, 2.0], [0.5, 1.5, 2.5, 2.0], [0.5, 1.5, 2.5, 2.0]]

In [6]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m] 
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [7]:
 c[1][1][0]

1

Note that combining objects in this way generally works with reference pointers to original objects

In [8]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [9]:
v[0]='Changed'
m

[['Changed', 0.75, 1.0, 1.5, 2.0],
 ['Changed', 0.75, 1.0, 1.5, 2.0],
 ['Changed', 0.75, 1.0, 1.5, 2.0]]

This can be avoided by using the deppcopy() function of the copy module

In [10]:
import copy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m=3*[copy.deepcopy(v)]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [11]:
v[0]='Changed'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

# <center>THE PYTHON ARRAY CLASS </center>

There is a dedicated array module in python

This module defines an object type which can compactly represent an array of basic
values: characters, integers, floating point numbers. Arrays are sequence types and
behave very much like lists, except that the type of objects stored in them is con‐
strained. The type is specified at object creation time by using a type code, which is a
single character.

In [12]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

import array

a=array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [13]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [14]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [15]:
2*a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In this case only float objects can be appended. Other types may raise errors

Another useful advantage of arrays is:

In [123]:
with open('array.apy', 'wb') as f:
    a.tofile(f)

# <center>REGULAR NUMPY ARRAYS</center>

Composing arrays with list objects works, but it is not really convenient.

The array class is a bit more specialized, providing useful features for working with arrays of data.

However, a truly specialized class would be best

numpy.ndarray is such a class, but with the specific goal of handling n-dimensional arrays both conveniently and efficiently

In [18]:
import numpy as np

a=np.array([0, 0.5, 0.75, 1.0, 1.5, 2.0])
a

array([0.  , 0.5 , 0.75, 1.  , 1.5 , 2.  ])

In [21]:
type(a)

numpy.ndarray

In [24]:
a=np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [26]:
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
a=np.arange(8,dtype=np.float32)
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [31]:
a[5:]

array([5., 6., 7.], dtype=float32)

In [32]:
a[:2]

array([0., 1.], dtype=float32)

A major feature of the ndarray class is the multitude of built-in methods:

In [34]:
a.sum()


np.float32(28.0)

In [36]:
a.std()

np.float32(2.291288)

In [38]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.], dtype=float32)

Another major feature is the (vectorized) mathematical operations defined on ndarray objects

In [40]:
l=[0, 0.5, 1.5, 3, 5]
2*l

[0, 0.5, 1.5, 3, 5, 0, 0.5, 1.5, 3, 5]

In [42]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [44]:
2*a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.], dtype=float32)

In [46]:
a**2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.], dtype=float32)

In [48]:
2**a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.], dtype=float32)

In [50]:
a**a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05], dtype=float32)

Another important feature of NumPy package are universal functions:

    They operate on ndarray objects as well as on basic data types of Python.
    However, when applying universal functions to, say, a Python float object, one needs to be aware of the reduced performance compared to the same functionality in the math module

In [52]:
np.exp(a)

array([1.0000000e+00, 2.7182820e+00, 7.3890557e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342877e+02, 1.0966332e+03],
      dtype=float32)

In [54]:
np.sqrt(a)

array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512], dtype=float32)

In [55]:
import math
math.sqrt(a)

TypeError: only 0-dimensional arrays can be converted to Python scalars

MULTIPLE DIMENSIONS

The transition to more than one dimension is seamless, and all features so far presented carry over

In [57]:
b=np.array([a,a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]], dtype=float32)

In [59]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [61]:
b[0,2]

np.float32(2.0)

In [63]:
b[:,1]

array([1., 2.], dtype=float32)

In [65]:
b.sum()

np.float32(84.0)

In [ ]:
b.sum(axis=0) #calculates sum collumn-wise

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.], dtype=float32)

In [ ]:
b.sum(axis=1) #calculates sum row-wise

array([28., 56.], dtype=float32)

There are several ways to initialize a ndarray object.
One is via np.array, however this assumes all elements of the array are already available.

In contrast, one might like to have the ndarray objects initialized first (empty) to populate them later with results generated during the execution of code.
For this, we can use the following functions

In [71]:
c=np.zeros((2,3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [73]:
c = np.ones((2, 3, 4), dtype='i', order='C') 
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [ ]:
d = np.zeros_like(c, dtype='float16', order='C') #differs from np.zeros because it takes the shape of c instead of the shape of the arguments
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float16)

In [77]:
e = np.empty((2, 3, 2)) 
e

array([[[2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314]],

       [[2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314]]])

In [78]:
f = np.empty_like(c) 
f

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [80]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
np.linspace(5, 15, 12)

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

METAINFORMATION

Every ndarray object provides access to a number of useful attributes:

In [84]:
c.size

24

In [85]:
c.itemsize

4

In [86]:
c.ndim

3

In [87]:
c.shape

(2, 3, 4)

In [88]:
c.dtype

dtype('int32')

In [89]:
c.nbytes

96

SHAPING AND RESIZING

Although ndarray objects are immutable by default, there are multiple options to reshape and resize them.
While reshaping in general just provides another view on the same data, resizing in general creates a new (temporary) object.

In [92]:
g=np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
g.shape

(15,)

In [96]:
np.shape(g)

(15,)

In [97]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
h=g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [100]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [101]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

During reshaping, the total number of observations is unchanged. During resizing, it changes:
Increases -- up-sizing
Decreases -- down-sizing

In [103]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
np.resize(g, (3,1))

array([[0],
       [1],
       [2]])

In [106]:
np.resize(g, (1,5))

array([[0, 1, 2, 3, 4]])

In [107]:
np.resize(g, (2, 5)) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
n = np.resize(g, (5, 4)) 
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

STACKING

Operation that allows the horizontal or vertical combination of 2 ndarray objects.
However, the size of the "connecting" dimension must be the same

In [110]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [112]:
np.hstack((h,2*h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [114]:
np.vstack((h,2*h))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

FLATTENING

Flattens a multi-dimensional array into a one-dimensional one.
One can choose whether the flattening happens row-by-row (C order) or column-by-column (F order)

In [116]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [118]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
h.flatten(order='C') #this is the default, it flattens row-wise

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

# <center>BOOLEAN ARRAYS</center>